### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by dojoMember** [SitePen/dgrid#1428]
I am loading a data into a store of  "**barcodeColumn**" data but when i change the value of "**labelAtrr**" into "**barcode**" it gives me this error
`dojo.js:15 TypeError: Cannot read property 'toString' of undefined
    at Object.labelFunc (_AutoCompleterMixin.js:256)
    at Object._getMenuLabelFromItem (_AutoCompleterMixin.js:239)
    at dojo.js:15
    at Object._createOption (_ComboBoxMenuMixin.js:31)
    at Object.<anonymous> (_ComboBoxMenuMixin.js:46)
    at Object.forEach (dojo.js:15)
    at Object.createOptions (_ComboBoxMenuMixin.js:45)
    at Object._openResultList (_AutoCompleterMixin.js:118)
    at Object._2ec (dojo.js:15)
    at Object._openResultList (FilteringSelect.js:24) "TypeError: Cannot read property 'toString' of undefined
    at Object.labelFunc (http://localhost:8080/core/resources/js/dijit/form/_AutoCompleterMixin.js:256:109)
    at Object._getMenuLabelFromItem (http://localhost:8080/core/resources/js/dijit/form/_AutoCompleterMixin.js:239:14)
    at http://localhost:8080/core/resources/js/dojo/dojo.js:15:114170
    at Object._createOption (http://localhost:8080/core/resources/js/dijit/form/_ComboBoxMenuMixin.js:31:8)
    at Object.<anonymous> (http://localhost:8080/core/resources/js/dijit/form/_ComboBoxMenuMixin.js:46:14)
    at Object.forEach (http://localhost:8080/core/resources/js/dojo/dojo.js:15:147925)
    at Object.createOptions (http://localhost:8080/core/resources/js/dijit/form/_ComboBoxMenuMixin.js:45:4)
    at Object._openResultList (http://localhost:8080/core/resources/js/dijit/form/_AutoCompleterMixin.js:118:15)
    at Object._2ec (http://localhost:8080/core/resources/js/dojo/dojo.js:15:66331)
    at Object._openResultList (http://localhost:8080/core/resources/js/dijit/form/FilteringSelect.js:24:6)`

and here is my code

`var barcodeColumn = {
    				field: 'barcode', 
    				label: dojoConfig.i18n.barcode, 
    				editor: Select,
    				autoSave: true,
    				editorArgs: {
    	    	                            searchAttr: 'barcode',
    	    	                            labelAttr: "barcode",
    			                   store: this.productObjStore
    				}
        		};

loadProducts: function(grid, rowData, newId){
    		return request.post(dojoConfig.urls.LOAD_PRODUCTS_SERVICES, {
    			handleAs: "json"
    			}).then(lang.hitch(this, function(data){
    				data=data.data;
				this.productStore.setData(data);
				this.productObjStore = new ObjectStore({objectStore: this.productStore});
    			}))
    	}`

**Comment by msssk** [comment]
This description does not clearly point to any bugs in dgrid. This is the dgrid bug tracker - if you can provide a test case that exposes a dgrid issue, we will look into it.

For usage and support questions, please use StackOverflow:
* [Dojo on StackOverflow](https://stackoverflow.com/questions/tagged/dojo)
* [dgrid on StackOverflow](https://stackoverflow.com/questions/tagged/dgrid)
